# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 967)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_prj = QtWidgets.QLabel(self.centralwidget)
        self.label_prj.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_prj.setObjectName("label_prj")
        self.verticalLayout_2.addWidget(self.label_prj)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButton_LoadRef = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LoadRef.setObjectName("pushButton_LoadRef")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_LoadRef)
        self.label_RefFile = QtWidgets.QLabel(self.centralwidget)
        self.label_RefFile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_RefFile.setObjectName("label_RefFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_RefFile)
        self.pushButton_LoadTarget = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LoadTarget.setObjectName("pushButton_LoadTarget")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_LoadTarget)
        self.label_TargetFile = QtWidgets.QLabel(self.centralwidget)
        self.label_TargetFile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_TargetFile.setObjectName("label_TargetFile")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_TargetFile)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_calcDiff = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calcDiff.setObjectName("pushButton_calcDiff")
        self.horizontalLayout_2.addWidget(self.pushButton_calcDiff)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeView_spreadSheets = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_spreadSheets.setObjectName("treeView_spreadSheets")
        self.verticalLayout_4.addWidget(self.treeView_spreadSheets)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_chartType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_chartType.setObjectName("comboBox_chartType")
        self.comboBox_chartType.addItem("")
        self.comboBox_chartType.addItem("")
        self.comboBox_chartType.addItem("")
        self.comboBox_chartType.addItem("")
        self.comboBox_chartType.addItem("")
        self.gridLayout.addWidget(self.comboBox_chartType, 1, 0, 1, 1)
        self.comboBox_chartData = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_chartData.setObjectName("comboBox_chartData")
        self.comboBox_chartData.addItem("")
        self.comboBox_chartData.addItem("")
        self.comboBox_chartData.addItem("")
        self.gridLayout.addWidget(self.comboBox_chartData, 1, 1, 1, 1)
        self.pushButton_delChart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delChart.setObjectName("pushButton_delChart")
        self.gridLayout.addWidget(self.pushButton_delChart, 2, 0, 1, 1)
        self.pushButton_addChart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addChart.setObjectName("pushButton_addChart")
        self.gridLayout.addWidget(self.pushButton_addChart, 1, 2, 1, 1)
        self.pushButton_showChart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_showChart.setObjectName("pushButton_showChart")
        self.gridLayout.addWidget(self.pushButton_showChart, 2, 1, 1, 2)
        self.treeView_charts = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_charts.setObjectName("treeView_charts")
        self.gridLayout.addWidget(self.treeView_charts, 0, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout, 7, 0, 1, 3)
        self.pushButton_delSheet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delSheet.setObjectName("pushButton_delSheet")
        self.gridLayout_4.addWidget(self.pushButton_delSheet, 4, 2, 1, 1)
        self.lineEdit_sheetName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sheetName.setText("")
        self.lineEdit_sheetName.setObjectName("lineEdit_sheetName")
        self.gridLayout_4.addWidget(self.lineEdit_sheetName, 3, 0, 1, 2)
        self.pushButton_addSheet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addSheet.setObjectName("pushButton_addSheet")
        self.gridLayout_4.addWidget(self.pushButton_addSheet, 3, 2, 1, 1)
        self.pushButton_showSheet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_showSheet.setObjectName("pushButton_showSheet")
        self.gridLayout_4.addWidget(self.pushButton_showSheet, 5, 2, 1, 1)
        self.comboBox_sheetType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sheetType.setObjectName("comboBox_sheetType")
        self.gridLayout_4.addWidget(self.comboBox_sheetType, 5, 0, 1, 1)
        self.comboBox_sheetGroup = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sheetGroup.setObjectName("comboBox_sheetGroup")
        self.gridLayout_4.addWidget(self.comboBox_sheetGroup, 5, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_newCounter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_newCounter.setObjectName("pushButton_newCounter")
        self.gridLayout_2.addWidget(self.pushButton_newCounter, 2, 1, 1, 1)
        self.pushButton_selectCounters = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectCounters.setObjectName("pushButton_selectCounters")
        self.gridLayout_2.addWidget(self.pushButton_selectCounters, 2, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_pfmonFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pfmonFilter.setText("")
        self.lineEdit_pfmonFilter.setObjectName("lineEdit_pfmonFilter")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pfmonFilter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_pfmonExpr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pfmonExpr.setObjectName("lineEdit_pfmonExpr")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pfmonExpr)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_pfmonNewName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pfmonNewName.setObjectName("lineEdit_pfmonNewName")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pfmonNewName)
        self.gridLayout_2.addLayout(self.formLayout_2, 1, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView_pfmonSelected = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_pfmonSelected.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView_pfmonSelected.setObjectName("treeView_pfmonSelected")
        self.verticalLayout.addWidget(self.treeView_pfmonSelected)
        self.lineEdit_pfmonSelectFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pfmonSelectFilter.setObjectName("lineEdit_pfmonSelectFilter")
        self.verticalLayout.addWidget(self.lineEdit_pfmonSelectFilter)
        self.pushButton_delSelectedCounters = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delSelectedCounters.setObjectName("pushButton_delSelectedCounters")
        self.verticalLayout.addWidget(self.pushButton_delSelectedCounters)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 1, 2)
        self.treeView_pfmons = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_pfmons.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView_pfmons.setObjectName("treeView_pfmons")
        self.gridLayout_2.addWidget(self.treeView_pfmons, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeView_batches = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_batches.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView_batches.setObjectName("treeView_batches")
        self.verticalLayout_3.addWidget(self.treeView_batches)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.pushButton_selBatches = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selBatches.setObjectName("pushButton_selBatches")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_selBatches)
        self.lineEdit_batchFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_batchFilter.setText("")
        self.lineEdit_batchFilter.setObjectName("lineEdit_batchFilter")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_batchFilter)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.treeView_batchSelected = QtWidgets.QTreeView(self.centralwidget)
        self.treeView_batchSelected.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeView_batchSelected.setObjectName("treeView_batchSelected")
        self.verticalLayout_3.addWidget(self.treeView_batchSelected)
        self.lineEdit_batchSelectedFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_batchSelectedFilter.setObjectName("lineEdit_batchSelectedFilter")
        self.verticalLayout_3.addWidget(self.lineEdit_batchSelectedFilter)
        self.pushButton_delBatches = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delBatches.setObjectName("pushButton_delBatches")
        self.verticalLayout_3.addWidget(self.pushButton_delBatches)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 26))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionSave)
        self.menuOpen.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.label_RefFile.setBuddy(self.pushButton_LoadRef)
        self.label_TargetFile.setBuddy(self.pushButton_LoadTarget)
        self.label_3.setBuddy(self.lineEdit_pfmonFilter)
        self.label.setBuddy(self.lineEdit_pfmonExpr)
        self.label_2.setBuddy(self.lineEdit_pfmonNewName)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_prj.setText(_translate("MainWindow", "Prj"))
        self.pushButton_LoadRef.setText(_translate("MainWindow", "Load Ref"))
        self.label_RefFile.setText(_translate("MainWindow", "RefFile"))
        self.pushButton_LoadTarget.setText(_translate("MainWindow", "Load Target"))
        self.label_TargetFile.setText(_translate("MainWindow", "TargetFile"))
        self.pushButton_calcDiff.setText(_translate("MainWindow", "CalcDiff"))
        self.label_4.setText(_translate("MainWindow", "Select:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Reference"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Target"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Diff"))
        self.comboBox_chartType.setItemText(0, _translate("MainWindow", "Table"))
        self.comboBox_chartType.setItemText(1, _translate("MainWindow", "Bar"))
        self.comboBox_chartType.setItemText(2, _translate("MainWindow", "Line"))
        self.comboBox_chartType.setItemText(3, _translate("MainWindow", "Scatter"))
        self.comboBox_chartType.setItemText(4, _translate("MainWindow", "Heatmap"))
        self.comboBox_chartData.setItemText(0, _translate("MainWindow", "Ref"))
        self.comboBox_chartData.setItemText(1, _translate("MainWindow", "Target"))
        self.comboBox_chartData.setItemText(2, _translate("MainWindow", "Diff"))
        self.pushButton_delChart.setText(_translate("MainWindow", "DeleteChart"))
        self.pushButton_addChart.setText(_translate("MainWindow", "AddChart"))
        self.pushButton_showChart.setText(_translate("MainWindow", "ShowChart"))
        self.pushButton_delSheet.setText(_translate("MainWindow", "DeleteSheet"))
        self.pushButton_addSheet.setText(_translate("MainWindow", "AddSheet"))
        self.pushButton_showSheet.setText(_translate("MainWindow", "Show"))
        self.pushButton_newCounter.setText(_translate("MainWindow", "New"))
        self.pushButton_selectCounters.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Names Filter"))
        self.label.setText(_translate("MainWindow", "Counter Expr"))
        self.label_2.setText(_translate("MainWindow", "Counter Name"))
        self.pushButton_delSelectedCounters.setText(_translate("MainWindow", "RemoveCounters"))
        self.pushButton.setText(_translate("MainWindow", "Select All"))
        self.pushButton_selBatches.setText(_translate("MainWindow", "AddBatchs"))
        self.pushButton_delBatches.setText(_translate("MainWindow", "RemoveBatches"))
        self.menuOpen.setTitle(_translate("MainWindow", "Project"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))

